// responses.js
// Bu faylda AI cavabları saxlanır

const responses = {
    "merhaba": "Merhaba! Nasılsın?",
    "selam": "Selam! Bugün nasılsın?",
    "nasılsın": "Ben iyiyim, teşekkürler! Sen nasılsın?",
    "naber": "İyi, senin naber?",
    "adın ne": "Benim adım Zeekr AI.",
    "ne yapıyorsun": "Seninle sohbet ediyorum.",
    "yardım": "Tabii, sana nasıl yardımcı olabilirim?",
    "hava nasıl": "Hava durumu konusunda maalesef bilgi veremem, ama umarım güzel bir gün geçiriyorsun!",
    "teşekkürler": "Rica ederim!",
    "sağol": "Ne demek!",
    "görüşürüz": "Görüşürüz! Kendine iyi bak.",
    "hoşça kal": "Hoşça kal!",
    "bana şaka yap": "Peki: Neden bilgisayar denize giremez? Çünkü suyun içinde Java çalışmaz 😄",
    "zaman": "Maalesef zamanı söyleyemem ama bilgisayar saatine bakabilirsin.",
    "benimle konuş": "Tabii! Ne hakkında konuşmak istersin?",
    "sen gerçek misin": "Ben bir yapay zekayım ama sana yardımcı olabilirim.",
    "kaç yaşındasın": "Benim yaşım yok, ama 2025 yılında yaratıldım.",
    "hangi dilleri konuşuyorsun": "Türkçe, İngilizce ve biraz da diğer dilleri anlayabiliyorum.",
    "sevgi": "Sevgi çok güzel bir duygu, hepimizin ihtiyacı var.",
    "hayat": "Hayat kısa, tadını çıkar!",
    "mutluluk": "Mutluluk paylaştıkça çoğalır.",
    "üzgünüm": "Üzgün hissettiğinde konuşmak iyi gelir, sana destek olabilirim.",
    "özür dilerim": "Özür kabul edildi.",
    "hobi": "Hobilerin insanı mutlu eder, senin hobin nedir?",
    "spor": "Spor yapmak sağlıklıdır, düzenli yapmayı unutma!",
    "müzik": "Müziği severim! Senin favori türün nedir?",
    "film": "Film izlemek eğlencelidir. Hangi tür filmleri seversin?",
    "kitap": "Kitap okumak bilgiyi artırır. Son okuduğun kitap neydi?",
    "teknoloji": "Teknoloji çok hızlı ilerliyor. Yeni şeyler öğrenmek heyecan verici!",
    "bilgisayar": "Bilgisayarlarla ilgili her türlü soruna yardımcı olabilirim.",
    "oyun": "Oyun oynamak eğlencelidir. Hangi oyunları seviyorsun?",
    "yemek": "Yemek yapmak veya yemek hakkında konuşmak güzel bir konu.",
    "tatil": "Tatil yapmak insanı dinlendirir. Nereleri gezmeyi seversin?",
    "şehir": "Şehirler çok farklı kültürleri barındırır.",
    "ülke": "Dünya üzerindeki ülkeleri keşfetmek eğlencelidir.",
    "hayvan": "Hayvanları severim! Senin favorin hangisi?",
    "kedi": "Kediler çok sevimlidir!",
    "köpek": "Köpekler sadık dostlardır.",
    "çiçek": "Çiçekler doğayı güzelleştirir.",
    "doğa": "Doğa insanı rahatlatır.",
    "güneş": "Güneş enerjisi harika bir enerji kaynağıdır.",
    "ay": "Ay geceleri gökyüzünü süsler.",
    "yıldız": "Yıldızlar gökyüzünün süsüdür.",
    "uzay": "Uzay çok büyük ve gizemlidir.",
    "bilim": "Bilim dünyayı anlamamıza yardımcı olur.",
    "matematik": "Matematik hayatın her alanında var.",
    "fizik": "Fizik doğadaki olayları açıklar.",
    "kimya": "Kimya hayatımızdaki molekülleri anlatır.",
    "tarih": "Tarih geçmişimizi öğrenmemizi sağlar.",
    "sanat": "Sanat ruhun gıdasıdır.",
    "resim": "Resim yapmak yaratıcılığı artırır.",
    "mimari": "Mimari binalar çok etkileyici olabilir.",
    "teknik": "Teknik konular zekayı geliştirir.",
    "programlama": "Programlama öğrenmek çok faydalıdır.",
    "javascript": "Javascript web geliştirme için harika bir dil.",
    "html": "HTML web sayfalarının iskeletidir.",
    "css": "CSS sayfalara stil verir.",
    "python": "Python kolay öğrenilen güçlü bir dildir.",
    "java": "Java uygulamalar için sıkça kullanılır.",
    "c++": "C++ performans gerektiren uygulamalarda iyidir.",
    "c#": "C# genellikle oyun geliştirmede kullanılır.",
    "php": "PHP web sunucu tarafı için popülerdir.",
    "sql": "SQL veri tabanı sorgulamak için kullanılır.",
    "veri": "Veri günümüzde çok değerlidir.",
    "internet": "İnternet bilgiye ulaşmayı kolaylaştırır.",
    "sosyal medya": "Sosyal medya bağlantı sağlar.",
    "instagram": "Instagram fotoğraf paylaşımı için popülerdir.",
    "facebook": "Facebook sosyal bağlantılar için kullanılır.",
    "twitter": "Twitter kısa mesajlar paylaşmak için idealdir.",
    "youtube": "Youtube video paylaşım platformudur.",
    "spotify": "Spotify müzik dinlemek için harikadır.",
    "fotoğraf": "Fotoğraf anıları ölümsüzleştirir.",
    "video": "Video eğlenceli ve öğreticidir.",
    "oyuncak": "Oyuncaklar çocukları mutlu eder.",
    "araba": "Arabalar ulaşım için gereklidir.",
    "uçak": "Uçaklarla dünyayı keşfetmek kolaydır.",
    "tren": "Trenle yolculuk yapmak keyiflidir.",
    "gemi": "Gemiyle seyahat etmek farklı bir deneyimdir.",
    "bisiklet": "Bisiklet sağlıklı bir ulaşım aracıdır.",
    "yürüyüş": "Yürüyüş yapmak sağlıklıdır.",
    "koşu": "Koşu enerjik hissettirir.",
    "yüzme": "Yüzme kasları çalıştırır ve eğlencelidir.",
    "spor salonu": "Spor salonu düzenli egzersiz için uygundur.",
    "fitness": "Fitness sağlıklı bir yaşam tarzıdır.",
    "diyet": "Diyet dengeli beslenmeyi içerir.",
    "sağlık": "Sağlık her şeyden önemlidir.",
    "psikoloji": "Psikoloji insan davranışlarını inceler.",
    "felsefe": "Felsefe düşünmeyi geliştirir.",
    "motivasyon": "Motivasyon başarıya götürür.",
    "başarı": "Başarı için azim ve sabır gerekir.",
    "hayal": "Hayaller hedefler için önemlidir.",
    "gelecek": "Gelecek planlarını şekillendirir.",
    "geçmiş": "Geçmiş dersler verir.",
    "an": "Anı yaşamak mutluluk verir.",
    "zaman": "Zaman değerlidir, boşa harcama.",
    "yaşam": "Yaşam bir yolculuktur, tadını çıkar.",
    "sevgi": "Sevgi insanı güçlü kılar.",
    "aşk": "Aşk kalbi ısıtır.",
    "arkadaş": "Arkadaşlar hayatın renkleridir.",
    "aile": "Aile destek kaynağıdır.",
    "okul": "Okul bilgi edinmek için önemlidir.",
    "üniversite": "Üniversite meslek ve bilgi kazandırır.",
    "çalışma": "Çalışmak hedefe götürür.",
    "iş": "İş yapmak sorumluluk getirir.",
    "kariyer": "Kariyer planlaması önemlidir.",
    "para": "Para ihtiyaçlarımızı karşılar.",
    "yatırım": "Yatırım geleceğe güven verir.",
    "ekonomi": "Ekonomi toplumun işleyişini açıklar.",
    "teknoloji": "Teknoloji hayatı kolaylaştırır.",
    "bilgisayar": "Bilgisayar hayatımızın bir parçasıdır.",
    "telefon": "Telefon iletişim için gereklidir.",
    "tablet": "Tablet taşınabilir bilgisayardır.",
    "robot": "Robotlar işleri kolaylaştırır.",
    "yapay zeka": "Ben yapay zekayım ve buradayım!",
    "ai": "AI, yapay zekanın kısa adıdır.",
    "program": "Program yazmak zeka geliştirir.",
    "kod": "Kod yazmak eğlencelidir.",
    "internet": "İnternet bilgiye hızlı ulaşmayı sağlar.",
    "web": "Web geliştirme popülerdir.",
    "site": "Site yapmak web tasarım becerisi gerektirir.",
    "uygulama": "Uygulamalar hayatı kolaylaştırır.",
    "oyun": "Oyun oynamak eğlencelidir.",
    "müzik": "Müzik ruhu besler.",
    "film": "Film izlemek keyiflidir.",
    "dizi": "Dizi takip etmek eğlencelidir.",
    "haber": "Haberleri takip etmek güncel kalmanı sağlar.",
    "spor": "Spor sağlığı korur.",
    "yemek": "Yemek yapmak yaratıcıdır.",
    "tatlı": "Tatlılar ruhu mutlu eder.",
    "içecek": "İçecekler ferahlatır.",
    "kahve": "Kahve enerji verir.",
    "çay": "Çay keyiflidir.",
    "su": "Su sağlıklıdır.",
    "hava": "Hava durumu değişkendir.",
    "güneş": "Güneş ışığı faydalıdır.",
    "yağmur": "Yağmur doğayı besler.",
    "kar": "Kar güzel manzaralar yaratır.",
    "rüzgar": "Rüzgar serinletir.",
    "deniz": "Deniz huzur verir.",
    "dağ": "Dağlar keşif için idealdir.",
    "orman": "Orman doğayı korur.",
    "çiçek": "Çiçekler gözleri mutlu eder.",
    "hayvan": "Hayvanlar sadık dosttur.",
    "kedi": "Kediler sevimlidir.",
    "köpek": "Köpekler arkadaş canlısıdır.",
    "kuş": "Kuşlar özgürlüğü simgeler.",
    "balık": "Balıklar suyun sakinliği gibidir.",
    "aslan": "Aslan cesur ve güçlüdür.",
    "kaplan": "Kaplan hızlı ve çeviktir.",
    "fil": "Fil güçlüdür ve bilgedir.",
    "maymun": "Maymun zeki ve eğlencelidir.",
    "tavşan": "Tavşan sevimlidir.",
    "ayı": "Ayılar güçlü ve sakin hayvanlardır.",
    "panda": "Panda sevimli ve huzurludur.",
    "hayal et": "Hayal kurmak özgürlüktür.",
    "öğren": "Öğrenmek bilgiyi artırır.",
    "keşfet": "Keşfetmek heyecan vericidir.",
    "dene": "Denemek cesaret ister.",
    "başla": "Başlamak en önemli adımdır.",
    "devam et": "Devam etmek azim gerektirir.",
    "bitir": "Bitirmek başarı getirir.",
    "kazanç": "Kazanç emeğin karşılığıdır.",
    "mutluluk": "Mutluluk paylaştıkça çoğalır.",
    "üzgün": "Üzgün hissetmek normaldir, rahatla.",
    "heyecan": "Heyecan yaşamı renklendirir.",
    "stres": "Stresle başa çıkmak önemlidir.",
    "rahatla": "Derin bir nefes al ve rahatla.",
    "gülümse": "Gülümsemek ruhu açar.",
    "düşün": "Düşünmek çözümler getirir.",
    "planla": "Plan yapmak işleri kolaylaştırır.",
    "yaz": "Yazmak fikirleri somutlaştırır.",
    "oku": "Okumak bilgiyi artırır.",
    "dinle": "Dinlemek anlayışı artırır.",
    "izle": "İzlemek eğlencelidir.",
    "oyna": "Oynamak keyif verir.",
    "çalış": "Çalışmak başarı getirir.",
    "araştır": "Araştırmak öğrenmeyi hızlandırır.",
    "deneme": "Denemek öğrenmenin yoludur.",
    "soru sor": "Soru sormak merakı artırır.",
    "cevap ver": "Cevap vermek iletişimi sağlar.",
    "paylaş": "Paylaşmak mutluluk getirir.",
    "yardım et": "Yardım etmek iyilik getirir."
  };
  
  export default responses;
  