name: Auto Push to GitHub
on:
  push:
    branches:
      - main  # Ana dalın ismi (eğer başka bir dal kullanıyorsan, onu yaz)
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Commit and Push Changes
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add .
        git commit -m "Auto commit: Güncellenen dosyalar"
        git push origin main
